services:
  postgres:
    container_name: postgres
    image: postgres:latest
    networks:
      red_interna:
        ipv4_address: 192.168.10.5
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB} #optional (specify default database instead of $POSTGRES_DB)
    ports:
      - "5433:5433"
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    networks:
      red_interna:
        ipv4_address: 192.168.10.6
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "50501:80"
    restart: always
networks:  
  red_interna:
     driver: bridge
     ipam:
       config:
        - subnet: "192.168.10.0/24"
          gateway: "192.168.10.1"